### ISSUE TITLE
role requires being or becoming root

### ISSUE THREAD

**Issue by timblaktu** [hussainweb/ansible-role-chezmoi#1]
I tried this role and found when run as normal user, the non-snap installation fails bc this requires sudo to run dpkg. IMO this role should become just for this task.

**Comment by hannah98** [comment]
+1
If I run this role as my username but set the role to become root, and set the chezmoi_init_url, it will initialize the chezmoi repository under the /root dir, not my own user's homedir.

**Comment by hussainweb** [comment]
If I am understanding this correctly, this is a simple change. Please take a look at the linked pull request.

**Comment by hannah98** [comment]
Perfect!  I was able to remove my workarounds - thanks for the change.
